# -*- mode: ruby -*-
# vi: set ft=ruby :

unless Vagrant.has_plugin?("vagrant-docker-compose")
  system("vagrant plugin install vagrant-docker-compose")
  puts "Dependencies installed, please try the command again."
  exit
end

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network :forwarded_port, host: 27017, guest: 27017
  config.vm.network :forwarded_port, host: 2113, guest: 2113
  config.vm.network :forwarded_port, host: 1113, guest: 1113
  config.vm.provision :docker
  config.vm.provision :docker_compose,
    yml: "/vagrant/docker-compose.yml",
    rebuild: true,
    project_name: "fiazard",
    run: "always"
end
