server:
#  softNofileLimit: 1000
#  hardNofileLimit: 1000
  applicationConnectors:
    - type: http
      port: 8080
#   - type: https
#     port: 8443
#     keyStorePath: example.keystore
#     keyStorePassword: example
#     validateCerts: false
  adminConnectors:
    - type: http
      port: 8081
#    - type: https
#      port: 8444
#      keyStorePath: example.keystore
#      keyStorePassword: example
#      validateCerts: false

# Mongo DB config.
mongo:
  uri: mongodb://localhost:27017/?maxPoolSize=50&maxIdleTimeMS=300000
  dbName: fiazard

eventStoreStreamURL: http://localhost:2113/streams/fiazard

# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:

    be.swsb.fiazard: DEBUG
    com.sun.jersey: DEBUG

#  appenders:
#    - type: console